#!gomplate

provider "google" {
    version     = "~> 1.20"
    project     = "{{ .Env.GCP_PROJECT_ID }}"
    region      = "{{ .Env.GCP_REGION }}"
}

provider "google-beta" {
    version     = "~> 2.5"
    project     = "{{ .Env.GCP_PROJECT_ID }}"
    region      = "{{ .Env.GCP_REGION }}"
}

terraform {
    backend "gcs" { 
        bucket = "{{ .Env.GCP_INFRASTRUCTURE_BUCKET }}"
        prefix = "{{ .Env.TF_BACKEND_PREFIX }}"
    }
}

# Prevent rebuild NAT by explicity define the template plugin version
# because template plugin change may alter the startup_scripts generated by the plugin
provider "template" {
    version     = "~> 1.0.0"
}
