apiVersion: v1
kind: Secret
metadata:
  namespace: ${APP_NAMESPACE}
  name: ${APP}-ssl
type: Opaque
data:
  tls.crt: %%${SEC_PATH}/${GCP_ENVIRONMENT}/ssl/server.crt%%
  tls.key: %%${SEC_PATH}/${GCP_ENVIRONMENT}/ssl/server.key%%
